services:
  spotify-monitor:
    build: .
    ports:
      - "${PORT:-8888}:8888"
    volumes:
      - ${CONFIG_PATH:-./.docker-config.json}:/app/config.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - spotify-network
    environment:
      - DB_HOST=spotify-shared-db
      - DB_PORT=5432
      - DB_NAME=spotify_data
      - DB_USER=${DB_USER:-spotify}
      - DB_PASSWORD=${DB_PASSWORD:-spotify_password}

networks:
  spotify-network:
    external: true
    name: spotify-shared-network

volumes:
  spotify-shared-db-data:
    external: true
    name: spotify-shared-db-data